---
title: "Datos de distritos de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme:
      version: 3
      bootswatch: cosmo
runtime: shiny   
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r paquetes, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(leaflet)
library(DT)
library(ggplot2)
library(leaflet)
library(plotly)
library(shiny)
```

```{r lectura_de_datos}
distritos <-
  st_read( dsn= "distritos_simplificados.geojson", quiet=TRUE) %>%
  st_transform(4326)
```

```{r lista_distritos}
# Lista ordenada de distritos + "Todas"
lista_provincias <- unique(distritos$provincias)
lista_provincias <- sort(lista_provincias)
lista_provincias <- c("Todas", lista_provincias)
```
```{r}
lista_cantones <- unique(distritos$cantones)
lista_cantones <- sort(lista_cantones)
lista_cantones <- c("Todas", lista_cantones)
```




Column {.sidebar}
----------------------------------------------------

```{r filtros}
# Selector de distrito
selectInput(
  inputId = "distrito",
  label = "Distritos",
  choices = lista_cantones,
  lista_provincias,
  selected = "Todas"
)

# Función para filtrar los datos con base en los controles de entrada
filtrarDistritos <- reactive({
  # Valor inicial del objeto que va a retornarse
  Distritos_filtrados <- distritos
  
  # Filtrado de cantones por distrito
  if (input$distritos != "Todas") {
    Distritos_filtrados <-
      Distritos_filtrados %>%
      filter(distritos == input$distritos)
  }
  
  return(Distrito_filtrados)
})
```

Row {data-height=10}
-----------------------------------------------

### **Fuente de los datos: [Instituto Geográfico Nacional (IGN)](http://geos.snitcr.go.cr/be/IGN_5/wfs)**

Row {data-height=590}
------------------------------

### mapa de cantones

```{r mapa}

renderLeaflet({
  distritos <- filtrarDistritos()
    
  leaflet() %>%
    setView(lng = -84.19452,
            lat = 9.572735,
            zoom = 7) %>%
    addTiles(group = "OpenStreetMap") %>%
    addPolygons(
      data = distritos,
      color = "black",
      opacity = 0.2,
      weight = 1.5,
      popup = paste(
        paste("<a>Cantón:</a>", distritos$distritos),
        paste("<a>Área:</a>", distritos$area, "km2"),
        sep = "<br>"
      ),
      group = "Distritos"
    ) %>%
    addLayersControl(baseGroups = c("OpenStreetMap"),
                     overlayGroups = c("Distritos"))
})
```
### tabla de cantones

```{r tabla}
# Tabla
renderDT({
  Distritos <- filtrarDistritos()
  
  Distritos %>%
    st_drop_geometry() %>%
    select(provincia, canton,distritos, area) %>%
    arrange(desc(area)) %>%
    datatable(
      colnames = c("Provincia", "Cantón","Distritos", "Área"),
      options = list(
        pageLength = 5,
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
      )
    )
})
```
Row {data-height=400}
-----------------------------------------------------------------------

### gráfico de cantones

```{r gráfico_de_cantones}
# Gráfico
renderPlotly({
  Distritos <- filtrarDistritos()
  
  grafico_ggplot2 <-
    cantones %>%
    st_drop_geometry() %>%
    slice_max(area, n = 20) %>%
    ggplot(aes(x = reorder(distrito,-area), y = area)) +
    geom_bar(stat = "identity") +
    xlab("Distrito") +
    ylab("Área (km2)")
  
  ggplotly(grafico_ggplot2)
})
```

